In [3]:
import numpy as np
import math
import numpy.random as rand  

# Задачи
*Стараться избегать циклы*
1. Отсортировать значения массива по частоте встречания.
2. Дана картинка высоты h, ширины w, тип данных np.uint8 (от 0 до 255). Найти количество уникальных цветов.
3. Написать функцию, вычислающую плавающее среднее вектора
4. Дана матрица (n, 3). Вывести те тройки чисел, которые являются длинами сторон треугольника.
5. Решить следующую систему линейных уравнений (не используя np.linalg.solve):
\begin{equation}
    \begin{matrix}
     \left\{
    \begin{matrix}
    3x + 4y + 2z = 17  \\
    5x + 2y + 3z = 23  \\
    4x + 3y + 2z = 19  \\ 
    \end{matrix} \right.
    \end{matrix}
\end{equation}

6.  Выполнить сингулярное разложение матрицы: \
A = np.matrix("1 0 1; 0 1 0; 1 0 1")

## Task1

### 1way

In [11]:
def sort_values_by_frequency(arr):
    unique, frequency = np.unique(arr, 
                              return_counts = True)
    frequency_list = frequency.tolist()
    unique_list = unique.tolist()
    d = dict(zip(unique_list,frequency_list))
    sorted_d = { k : d[k] for k in sorted(d.keys(), key = d.get )} # получаем отсортированный по частоте словарь вида {число : частота}
    result = [x for x in sorted_d for _ in range (sorted_d[x])]
    print(result)

In [12]:
arr = rand.randint(0,5,(3,3))
print(arr)
sort_values_by_frequency(arr)

[[2 4 0]
 [3 0 2]
 [1 4 0]]
[1, 3, 2, 2, 4, 4, 0, 0, 0]


### 2way

In [91]:
unique, frequency = np.unique(arr, 
                              return_counts = True)
sortIdx = np.argsort(frequency)
print(unique[sortIdx])

[2 3 1 4]


## Task2

In [103]:
h, w = 32, 32
arr = rand.uniform(0, 255, (h,w))
arr = arr.astype(np.uint8)
unique = np.unique(arr)
print(len(unique))

251


## Task3

### 1way

In [16]:
def moving_avg(vector, window_size) :
    res = []
    for i in range(len(vector) - window_size + 1):
        start = i
        end = i + window_size
        res.append(np.mean(vector [start:end]))
    return res
    
vec = np.array([1,2,3,4,5,6,7,8,9], dtype = float)
window = 3
res = moving_avg(vec,window)
res = list(map(float,res))
print(res)


[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]


### 2way

In [26]:
smoothed = np.convolve(vec, np.ones(window)/window,  'valid')


## Task4

In [28]:
def is_side_triangle(row):
    return row[0]<row[1] + row[2] and row[1]<row[0] + row[2] and row[2]<row[0] + row[1]

In [30]:
n = 10
matrix = rand.uniform(1,100, (n,3))
matrix = matrix.astype(np.uint32)
matrix_filter = np.apply_along_axis(is_side_triangle, axis = 1, arr = matrix) ## axis = 1 функция приминяется к каждой строке , 0 - cтолбцу , 2 - слою ...
filtered_matrix = matrix[matrix_filter]
print(filtered_matrix)

[[96 42 99]
 [83 42 67]
 [43 72 91]
 [80 78 25]
 [81 59 53]]


## Task5

### метод гаусса

In [194]:
def strsub(matrix, N, strDec, staticStr, jStart, coef) :
    for j in range (jStart, N+1):
        matrix[strDec][i] =  matrix[strDec][i] - matrix[staticStr][i] * coef

In [31]:
import numpy as np

def strsub(matrix, N, strDec, staticStr, jStart, coef):
    for j in range(jStart, N + 1):
        matrix[strDec][j] = matrix[strDec][j] - matrix[staticStr][j] * coef
    print(matrix)
    print()


matrix = np.array([[5, 2, 3, 23],
                   [3, 4, 2, 17],
                   [4, 3, 2, 19]])

# matrix = np.array([[2,1,-1,8],
## [-3,-1,2,-11],
# [-2,1,2,-3]] ,dtype= float)
N = len(matrix)

for i in range(N):
    k = N - 1
    while (matrix[i][i] == 0 and k != 0):
        strsub(matrix, N, i, k, 0, 1.0)
        k -= 1
    for j in range(i + 1, N):
        c = matrix[j][i] / matrix[i][i]
        strsub(matrix, N, j, i, i, c)



for i in range(N - 1, -1, -1):
    sum = 0
    for j in range(i + 1, N):
        sum += matrix[i][j] * matrix[j][N]
    matrix[i][N] = (matrix[i][N] - sum) / (matrix[i][i] + 1e-5)

print(matrix)

print(matrix[0][N])
print(matrix[1][N])
print(matrix[2][N])    

[[ 5  2  3 23]
 [ 0  2  0  3]
 [ 4  3  2 19]]

[[ 5  2  3 23]
 [ 0  2  0  3]
 [ 0  1  0  0]]

[[ 5  2  3 23]
 [ 0  2  0  3]
 [ 0  0  0 -1]]

[[ 5  2  3 23]
 [ 0  2  0  3]
 [ 0  0  0  0]]

[[ 5  2  3 23]
 [ 0  2  0  3]
 [ 0 -2  0 -3]]

[[      5       2       3  180003]
 [      0       2       0       1]
 [      0      -2       0 -300000]]
180003
1
-300000


### метод Краммера

In [269]:
def new_matrix(original_matrix, idx, newcolumn):
    new_matrix = original_matrix.copy()
    new_matrix[:, idx] = newcolumn

    return new_matrix
    
def Crammer(matrix, value):
    det_matrix = np.linalg.det(matrix)
    res = []
    for i in range (len(matrix)):
        temp = new_matrix(matrix,i,value) 
        det_temp = np.linalg.det(temp)
        res.append(det_temp/det_matrix)
        
    res = list(map(round, res))
    print(res)
    

In [270]:
matrix = np.array([[3,4,2],
                  [5,2,3],
                 [4,3,2]], dtype = float)
value = np.array([17,23,19], dtype = float)
Crammer(matrix,value)

[3, 1, 2]


### Матричный метод

In [286]:
matrix = np.array([[3,4,2],
                  [5,2,3],
                 [4,3,2]], dtype = float)
value = np.array([17,23,19], dtype = float)
matrix_inv = np.linalg.inv(matrix)
res = np.matmul(matrix_inv, value)
print(res)

[3. 1. 2.]


## Task6

### Сингулярное разложение матрицы

Сингулярное разложение матрицы (SVD, Singular Value Decomposition) — это метод в линейной алгебре, который позволяет разложить любую матрицу на произведение трех матриц: ортогональной матрицы, диагональной матрицы и еще одной ортогональной матрицы. Формально, для любой матрицы \( A \) размера \\( m \times n \\) существует разложение:

\\[ A = U \Sigma V^T \\]

где:
- \\( U \\) — ортогональная матрица размера \\( m \times m \\),
- \\( \Sigma \\) — диагональная матрица размера \\( m \times n \\),
- \\( V \\) — ортогональная матрица размера \\( n \times n \\).

Матрица \\( \Sigma \\) содержит сингулярные значения матрицы \\( A \\) на диагонали, а остальные элементы равны нулю. Сингулярные значения — это неотрицательные числа, которые упорядочены по убыванию.

In [24]:
A = np.array([[1,0,1],
             [0,1,0],
             [1,0,1]], dtype=float)
U, s_vec, Vtr = np.linalg.svd(A)
s_matrix = np.zeros((3, 3))
s_matrix[np.diag_indices(3)] = s_vec



In [25]:
print(np.matmul(np.matmul(U, s_matrix), Vtr) )

[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [33]:
np.random.seed(18182)
b = np.random.randint(5, size=(2, 3))
print('Исходный:\n', b)
x = np.where(b > 2)
print(b[x])

Исходный:
 [[2 3 3]
 [4 1 1]]
[3 3 4]


In [52]:

list2 = [1,2,3,4,5,6,7,8,9]
P = 0.7
freq_in_list2 = np.random.uniform(0,1,size = (1,len(list2)))
print(freq_in_list2)
mask = np.where(freq_in_list2 > P, True, False)
mask = mask.tolist()

[[0.31987114 0.84651651 0.46961074 0.05927739 0.17190478 0.58687235
  0.5603574  0.34345002 0.81774277]]
